name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - 'projects/ng-text-highlight/**'
      - '.github/**'

jobs:
  build-and-publish-to-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build library and app
        run: |
          npm run build:library
          npm run build:prod

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Publish Library to npm
        run: |
          cd dist/ng-text-highlight
          PKG_NAME=$(node -p "require('./package.json').name")
          PKG_VERSION=$(node -p "require('./package.json').version")

          echo "Checking if version $PKG_VERSION of $PKG_NAME already exists on npm..."

          if npm view "$PKG_NAME@$PKG_VERSION" > /dev/null 2>&1; then
            echo "::warning ::Version $PKG_VERSION of $PKG_NAME already exists. Skipping publish."
          else
            npm publish
          fi

      - name: Create Release Tag (optional)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag v$(date +'%Y%m%d%H%M%S')
          git push origin --tags
